/* Generated by tools/img2rgb565.py from bt_source.png, do not edit. */

#pragma once

#include <stdint.h>

#define BT_ICON_WIDTH  26
#define BT_ICON_HEIGHT 36

/* RGB565 in host order, row major, for gc9a01a_draw_bitmap(). */
extern const uint16_t bt_icon[BT_ICON_WIDTH * BT_ICON_HEIGHT];
