/* Generated by tools/img2rgb565.py from dog_source.png, do not edit. */

#pragma once

#include <stdint.h>

#define DOG_LARGE_WIDTH  144
#define DOG_LARGE_HEIGHT 188

/* RGB565 in host order, row major, for gc9a01a_draw_bitmap(). */
extern const uint16_t dog_large[DOG_LARGE_WIDTH * DOG_LARGE_HEIGHT];
