/* Generated by tools/img2rgb565.py from dog_source.png, do not edit. */

#pragma once

#include <stdint.h>

#define DOG_BADGE_WIDTH  67
#define DOG_BADGE_HEIGHT 88

/* RGB565 in host order, row major, for gc9a01a_draw_bitmap(). */
extern const uint16_t dog_badge[DOG_BADGE_WIDTH * DOG_BADGE_HEIGHT];
